#!/usr/bin/env python3
"""Generate a pinned-model manifest (repository, revision, per-file SHA-256).

Auditable way to (re)produce worker/models/*.manifest.json when the pinned
revision is intentionally advanced (which REQUIRES bumping the analyzer bundle
version, e.g. speech-6 -> speech-7). Downloads the exact revision, hashes the
load-required files, and prints the manifest JSON to stdout. Run where the Hub is
reachable (a CI dispatch job or a networked box); commit the output; the build's
fetch_model.py then independently re-verifies it.

  python3 gen_model_manifest.py --repo Systran/faster-whisper-small \
      --revision <40-char-sha> > worker/models/faster-whisper-small.manifest.json

Needs huggingface_hub (already a faster-whisper dependency). Stdlib otherwise.
"""
import argparse
import hashlib
import json
import os
import re
import sys

# Files faster-whisper actually loads for a CTranslate2 Whisper snapshot.
REQUIRED = ["model.bin", "config.json", "tokenizer.json", "vocabulary.txt"]


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--revision", required=True, help="full 40-char commit sha")
    ap.add_argument("--license", default="MIT")
    ap.add_argument("--analyzer-bundle", required=True,
                    help="analyzer bundle this pin is coupled to (e.g. speech-7) — must equal the default speechVersion")
    args = ap.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.revision):
        print("ERROR: --revision must be exactly [0-9a-f]{40}", file=sys.stderr)
        sys.exit(2)

    from huggingface_hub import snapshot_download
    local = snapshot_download(repo_id=args.repo, revision=args.revision)

    files = {}
    for name in REQUIRED:
        p = os.path.join(local, name)
        if not os.path.isfile(p):
            print(f"ERROR: expected file missing at {args.repo}@{args.revision}: {name}", file=sys.stderr)
            sys.exit(1)
        files[name] = sha256_file(p)

    man = {
        "_comment": "PINNED Faster-Whisper snapshot for the immutable Phase 5 speech "
                    "component. Generated by gen_model_manifest.py; re-verified by "
                    "fetch_model.py at build. Advancing the revision REQUIRES a speechVersion bump.",
        "repository": args.repo,
        "revision": args.revision,
        "license": args.license,
        "analyzerBundle": args.analyzer_bundle,
        "files": files,
    }
    print(json.dumps(man, indent=2))


if __name__ == "__main__":
    main()
