// Editor v2 — isolated namespace (see docs/twinai-new-editor-build-plan.md §6).
// Only wire/domain contracts and the client start/observe API live here; worker
// internals stay private to worker/src/editor. This module must never import
// recording-timeline adapters or any legacy editor code.
export * from './contracts'
export * from './api'
export * from './features'
export * from './director'
export * from './capture'
export * from './captureProvenance'
export * from './scriptSnapshot'
export * from './sourceCreate'
export * from './catalogs'
export * from './brandSnapshot'
export * from './review'
export * from './capabilities'
export * from './glossary'
export * from './outcomes'
export * from './attribution'
export * from './renderCost'
export * from './referenceCheck'
export * from './craftChecks'
export * from './outputBundle'
export * from './finishedOutput'
export * from './approval'
export * from './craftFacts'
export * from './failureExplain'
export * from './aspectIntent'
export * from './uploadCeiling'
