// Deterministic real media inputs for the render harness.
//
// THE FIXTURE IS 60 SECONDS ON PURPOSE. It is the media counterpart of
// `__tests__/fixtures/editPlanFixture.ts`, whose 60 s source, accepted windows
// [0,20000) and [25000,50000), and hand-derived EXPECTED segment table are
// already proven by the offline suite. Rendering THAT plan means every source
// boundary, every removal and every output timestamp in the rendered file is
// known in advance rather than whatever a fresh ad-hoc input happened to produce.
//
// Both fixtures carry a MONOTONIC VISUAL CLOCK and a KNOWN AUDIO SIGNAL, because
// the evidence downstream is decoded pixels and decoded PCM — not container
// metadata. The clock is what makes the strongest claim in the harness testable:
// that an output frame shows the SOURCE time the plan says it should, i.e. that
// the cuts actually removed the bytes they promised to remove.
//
// Everything here is generated by ffmpeg itself from lavfi sources, so the inputs
// are reproducible on any machine with the same ffmpeg, and no binary blobs enter
// the repository.
import { execFileSync } from 'node:child_process'
import { mkdirSync, existsSync } from 'node:fs'
import { join } from 'node:path'

/** Source raster. Exactly 9:16, so the graph's scale+centre-crop is a pure 2x
 *  upscale to 1080x1920 and source coordinates map to output by a factor of 2. */
export const SRC_W = 540
export const SRC_H = 960

// ---- the visual clock ------------------------------------------------------
//
// A BINARY CLOCK, not a moving bar. The obvious design — one box whose x is a
// linear function of time — DOES NOT WORK, and that was established by running
// it: `drawbox` evaluates x/y/w/h ONCE at configuration, where the timestamp is
// unknown, so `x='8*t'` is NaN and the box is never drawn at all. Decoded frames
// contained no bar whatsoever. (Same family as the crop-vs-zoompan defect: the
// filter accepts the expression and silently does nothing with it.)
//
// `enable`, by contrast, IS evaluated per frame — that is the whole point of the
// timeline system. So the clock is ten FIXED boxes, each toggled by one bit of
// floor(t*10). Reading them back gives the source time in 100 ms units, exactly,
// with no sub-pixel measurement and nothing that compression can smear.
export const CLOCK_BITS = 10
export const CLOCK_TICK_MS = 100
export const CLOCK_Y0 = 80
export const CLOCK_Y1 = 160
export const CLOCK_BLOCK_W = 40
export const CLOCK_PITCH = 50
export const CLOCK_X0 = 40
/** Centre of bit `b`'s block, in source pixels (== decoded pixels at 540x960). */
export function clockBitCentreX(b: number): number {
  return CLOCK_X0 + b * CLOCK_PITCH + CLOCK_BLOCK_W / 2
}
export const CLOCK_CENTRE_Y = (CLOCK_Y0 + CLOCK_Y1) / 2

export interface Fixture {
  /** 'teleprompter' = one continuous take; 'upload' = a visually distinct capture. */
  kind: 'teleprompter' | 'upload'
  path: string
  durationMs: number
  /** Sine frequency of the fixture's tone; checked against decoded PCM. */
  toneHz: number
}

/**
 * The ten-bit clock plus a colour band that steps every 10 s.
 *
 * The clock sits in the TOP band and the colours in the BOTTOM band, so neither
 * collides with burned-in captions (which the plan places against the bottom
 * margin) — a caption must not be able to masquerade as clock motion, and the
 * clock must not be overdrawn by a caption.
 */
function videoSource(durationSec: number, phase: number): string {
  const bands = ['red', 'green', 'blue', 'yellow', 'magenta', 'cyan']
  const filters = [`color=c=#101018:s=${SRC_W}x${SRC_H}:r=30:d=${durationSec}`]
  for (let b = 0; b < CLOCK_BITS; b++) {
    filters.push(
      `drawbox=x=${CLOCK_X0 + b * CLOCK_PITCH}:y=${CLOCK_Y0}`
      + `:w=${CLOCK_BLOCK_W}:h=${CLOCK_Y1 - CLOCK_Y0}:color=white@1.0:t=fill`
      + `:enable='gt(bitand(floor(t*${1000 / CLOCK_TICK_MS}),${2 ** b}),0)'`,
    )
  }
  for (let i = 0; i < bands.length; i++) {
    // `phase` rotates which colour lands in which decade, so a frame from the
    // upload fixture can never be confused with one from the teleprompter fixture.
    const c = bands[(i + phase) % bands.length]
    filters.push(
      `drawbox=x=0:y=380:w=${SRC_W}:h=120:color=${c}@1.0:t=fill:enable='between(t,${i * 10},${(i + 1) * 10})'`,
    )
  }
  return filters.join(',')
}

export function buildFixtures(dir: string, ffmpeg = 'ffmpeg'): Record<string, Fixture> {
  mkdirSync(dir, { recursive: true })
  const out: Record<string, Fixture> = {}

  // 60 s each: the compile fixture's source duration. A shorter fixture would put
  // the plan's later segments past the end of the file, and the renderer would be
  // proven against a source it will never see.
  const specs: Array<{ kind: Fixture['kind']; sec: number; toneHz: number; phase: number }> = [
    { kind: 'teleprompter', sec: 60, toneHz: 440, phase: 0 },
    { kind: 'upload', sec: 60, toneHz: 660, phase: 3 },
  ]

  for (const s of specs) {
    const path = join(dir, `${s.kind}.mp4`)
    if (!existsSync(path)) {
      execFileSync(ffmpeg, [
        '-hide_banner', '-loglevel', 'error', '-nostdin',
        '-f', 'lavfi', '-i', videoSource(s.sec, s.phase),
        // Known audio: a pure tone at a known frequency and amplitude, so a
        // dropped or silenced audio path cannot pass the PCM checks.
        '-f', 'lavfi', '-i', `sine=frequency=${s.toneHz}:sample_rate=48000:duration=${s.sec}`,
        '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
        // The clock must be readable at every sampled instant, so keyframes are
        // frequent and quality is high: a smeared bit would read as a wrong time.
        '-crf', '18', '-g', '30',
        '-c:a', 'aac', '-ac', '2', '-ar', '48000',
        '-t', String(s.sec), path, '-y',
      ], { stdio: ['ignore', 'ignore', 'pipe'] })
    }
    out[s.kind] = { kind: s.kind, path, durationMs: s.sec * 1000, toneHz: s.toneHz }
  }
  return out
}
