/**
 * THE NUMBER NOBODY HAD WRITTEN DOWN.
 *
 * ⚠️ FROZEN EVIDENCE, NOT A TARGET. The four audited live runs are the proof
 * that the reference-use control did not govern content borrowing: every one of
 * them was generated by the shipped writer, against the same reference, and the
 * overlap below is what they actually exhibit. These assertions are pinned to
 * the runs as they are, so that when the mechanism changes what the writer sees,
 * the change has a measured "before" to be compared against instead of an
 * argument.
 *
 * ⚠️ THESE FIXTURES ARE PRE-FIX ARTEFACTS AND MUST NOT MOVE. They record
 * generations that already happened. Nothing in this change regenerates them,
 * so every number here is expected to be stable; a diff in this file means
 * either a fixture was edited or the MEASURE was changed, and both need saying
 * out loud rather than re-freezing.
 *
 * ⚖️ WHAT THIS FILE CANNOT SHOW. It cannot show the reduction. The fix removes
 * verbatim text from the WRITER'S PROMPT, and observing the effect of that
 * requires generating new scripts, which requires a model key this environment
 * does not have. The final test in this file is the named, ready-to-run
 * comparison that will show it the moment someone with a key executes it — it
 * is deliberately not asserting an improvement nobody has observed.
 */
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { measureVerbatimOverlap, HIGH_OVERLAP_RUN_WORDS } from '../script/verbatimOverlap.js'

const RUNS = ['a', 'b', 'c', 'd'] as const

function loadRun(id: (typeof RUNS)[number]) {
  const path = fileURLToPath(new URL(`../../../../eval/fixtures/live-runs/run-${id}.json`, import.meta.url))
  return JSON.parse(readFileSync(path, 'utf8')) as {
    settings: { fidelity?: string | null }
    reference: { text: string }
    generation: { blueprint: { script: Array<{ line?: unknown }> } }
  }
}

/**
 * ⚠️ MEASURED 2026-08-30 against the four fixtures at their frozen content, by
 * `measureVerbatimOverlap`. `longestRun` counts CONTENT words shared
 * contiguously and in order with the reference transcript; `high` counts script
 * sentences reaching the ≥6-content-word copying threshold.
 */
const BASELINE: Record<(typeof RUNS)[number], {
  longestRun: number; sentences: number; high: number; share: number; setting: string
}> = {
  // Ran at the setting the audit reports as the LOOSEST available, and still
  // carried a nine-content-word run of the reference creator's own sentence.
  a: { longestRun: 9, sentences: 7, high: 1, share: 0.1429, setting: 'just_how_it_is_built' },
  // The one clean run on this axis. Its defects are elsewhere (markdown in a
  // spoken line, coaching panels describing the reference's structure) — which
  // is why a borrowing measure must be able to report ZERO as well as a number.
  b: { longestRun: 1, sentences: 5, high: 0, share: 0, setting: 'just_how_it_is_built' },
  c: { longestRun: 8, sentences: 8, high: 1, share: 0.125, setting: 'close_to_the_reference' },
  // ⚠️ THE WORST, AND THE WHOLE ARGUMENT. Seventeen consecutive content words of
  // the reference creator's own sentence, in his order, in a creator's script —
  // at the setting the creator chose to get the LEAST of the reference.
  d: { longestRun: 17, sentences: 6, high: 2, share: 0.3333, setting: 'undefined' },
}

describe('reference borrowing in the four live runs — frozen baseline', () => {
  for (const id of RUNS) {
    it(`run-${id} exhibits exactly the overlap recorded for it`, () => {
      const run = loadRun(id)
      const r = measureVerbatimOverlap(run.generation.blueprint.script, run.reference.text)
      const want = BASELINE[id]
      expect({
        longestRun: r.longestRun, sentences: r.sentences,
        high: r.highOverlapSentences, share: r.highOverlapShare,
      }).toEqual({
        longestRun: want.longestRun, sentences: want.sentences,
        high: want.high, share: want.share,
      })
      expect(String(run.settings.fidelity)).toBe(want.setting)
    })
  }

  it('records that borrowing happened at the LOOSEST setting, which is the defect', () => {
    // This is the assertion the rename could not have made. Three of four runs
    // carried a run of the reference's own words, and the two worst were not
    // set to "stay close" — so the control was not governing borrowing at all.
    const carried = RUNS.filter((id) => {
      const run = loadRun(id)
      return measureVerbatimOverlap(run.generation.blueprint.script, run.reference.text)
        .longestRun >= HIGH_OVERLAP_RUN_WORDS
    })
    expect(carried).toEqual(['a', 'c', 'd'])
  })

  it('reports the corpus-wide baseline share, the headline number', () => {
    let sentences = 0, high = 0, worst = 0
    for (const id of RUNS) {
      const run = loadRun(id)
      const r = measureVerbatimOverlap(run.generation.blueprint.script, run.reference.text)
      sentences += r.sentences; high += r.highOverlapSentences
      worst = Math.max(worst, r.longestRun)
    }
    // 4 of 26 script sentences across the four runs reproduce a ≥6-content-word
    // run of the reference creator's speech; the longest is 17 words.
    expect({ sentences, high, worst }).toEqual({ sentences: 26, high: 4, worst: 17 })
    expect(Math.round((high / sentences) * 10000) / 10000).toBe(0.1538)
  })
})

/**
 * THE TEST THAT WILL SHOW THE REDUCTION — UNRUN, AND SAID SO.
 *
 * ⚠️ THIS ENVIRONMENT HAS NO `GEMINI_API_KEY`, so the writer cannot be executed
 * and NO REDUCTION HAS BEEN OBSERVED. Everything shipped alongside this file is
 * the mechanism and the measure; the effect is unmeasured. This test names the
 * comparison precisely enough that anyone with a key can settle it, and it
 * SKIPS rather than passing vacuously — a green tick nobody earned is how the
 * previous version of this control shipped looking correct.
 */
describe('the reduction this change predicts (requires a model key)', () => {
  const key = process.env.GEMINI_API_KEY
  it.skipIf(!key)(
    'generating run-D s brief at reference_use=structure yields a lower longestRun than 17',
    () => {
      // Deliberately unimplemented rather than faked. To settle this: re-run
      // run-D's brief and reference through `generate-blueprint` with
      // `reference_use: 'structure'`, then assert
      //   measureVerbatimOverlap(script, run.reference.text).longestRun
      // is below the frozen baseline of 17, and that highOverlapSentences is 0.
      expect(key, 'a key is present but this comparison is not wired to the edge function yet').toBeTruthy()
      throw new Error('UNWIRED: run generate-blueprint against run-D at reference_use=structure and compare to BASELINE.d')
    },
  )

  it('states plainly, in the suite output, that the reduction is unmeasured here', () => {
    expect(process.env.GEMINI_API_KEY ?? '').toBe('')
  })
})
