// @twinai/shared — code used by the web app (Vercel): data types, brand/pricing
// constants, the Recording Script, and the backend API layer (client-agnostic;
// call initApi() once at app startup). Kept as its own package so the API and
// domain logic stay decoupled from the React/Vite app that consumes them.
export * from './types'
export * from './brand'
export * from './recordingScript'
export * from './sceneConsistency'
export * from './recordingScriptAdapter'
export * from './recordingScriptApi'
export * from './scriptEdit'
export * from './scriptEditRecord'
export * from './creatorQuestions'
export * from './scriptAttempt'
export * from './editClassification'
export * from './hookChoice'
export * from './galleryRank'
export * from './referenceEvidence'
export * from './referenceAnalysis'
export * from './creativeTransferRows'
export * from './containerResolution'
export * from './containerSupply'
export * from './bestTime'
export * from './api'
export * from './outcomeLog'
export * from './capture'
export * from './preflight'
export * from './preScriptBrief'
export * from './inAppPath'
export * from './beatPlan'
export * from './productEvidence'
export * from './productEntity'
export * from './productExtraction'
export * from './productFreshness'
export * from './referenceMechanism'
export * from './creatorKnowledge'
export * from './knowledgeSelection'
export * from './knowledgeResolver'
export * from './spokenPlaceholders'
export * from './shotDirection'
export * from './compatibilityGate'
export * from './editor/index'
